<option value="0" hidden selected>Model Mobilnog Telefona</option>
<option value="iPhone 14 Pro Max">iPhone 14 Pro Max</option>
<option value="iPhone 14 Pro">iPhone 14 Pro</option>
<option value="iPhone 14">iPhone 14</option>
<option value="iPhone SE (3.gen)">iPhone SE (3.gen)</option>
<option value="iPhone 13 Pro Max">iPhone 13 Pro Max</option>
<option value="iPhone 13 Pro">iPhone 13 Pro</option>
<option value="iPhone 13">iPhone 13</option>
<option value="iPhone 13 mini">iPhone 13 mini</option>
<option value="iPhone 12 Pro Max">iPhone 12 Pro Max</option>
<option value="iPhone 12 Pro">iPhone 12 Pro</option>
<option value="iPhone 12">iPhone 12</option>
<option value="iPhone 12 mini">iPhone 12 mini</option>
<option value="iPhone SE (2.gen)">iPhone SE (2.gen)</option>
<option value="iPhone 11 Pro Max">iPhone 11 Pro Max</option>
<option value="iPhone 11 Pro">iPhone 11 Pro</option>
<option value="iPhone 11">iPhone 11</option>
<option value="iPhone XS Max">iPhone XS Max</option>
<option value="iPhone XS">iPhone XS</option>
<option value="iPhone XR">iPhone XR</option>
<option value="iPhone X">iPhone X</option>
<option value="iPhone 8 Plus">iPhone 8 Plus</option>
<option value="iPhone 8">iPhone 8</option>
<option value="iPhone 7 Plus">iPhone 7 Plus</option>
<option value="iPhone 7">iPhone 7</option>
<option value="iPhone 6s Plus">iPhone 6s Plus</option>
<option value="iPhone 6s">iPhone 6s</option>
<option value="iPhone 6">iPhone 6</option>
<option value="iPhone 5s">iPhone 5s</option>
<option value="iPhone 5c">iPhone 5c</option>
<option value="iPhone 5">iPhone 5</option>