<option value="1">Galaxy S23 Ultra</option>
<option value="2">Galaxy S23</option>
<option value="3">Galaxy Z Fold 4</option>
<option value="4">Galaxy Z Flip 4</option>
<option value="5">Galaxy S22 Ultra</option>
<option value="6">Galaxy S22+</option>
<option value="7">Galaxy S22</option>
<option value="8">Galaxy S20 FE 5G</option>
<option value="9">Galaxy S21 Ultra</option>
<option value="10">Galaxy s21 FE 5G</option>
<option value="11">Galaxy S20 FE</option>
<option value="12">Galaxy Note 20 Ultra 5G</option>
<option value="13">Galaxy S20+</option>
<option value="14">Galaxy S20 Ultra</option>
<option value="15">Galaxy Note 10+</option>
<option value="16">Galaxy S10e</option>
<option value="17">Galaxy S10+</option>
<option value="18">Galaxy S10</option>
<option value="19">Galaxy Note 9</option>
<option value="20">Galaxy Note S9+</option>
<option value="21">Galaxy S9</option>
<option value="22">Galaxy Note 8</option>
<option value="23">Galaxy S8+</option>
<option value="24">Galaxy S8</option>
<option value="25">Galaxy C9 Pro</option>
<option value="26">Galaxy S7 Edge</option>
<option value="27">Galaxy S7</option>
<option value="28">Galaxy A8</option>
<option value="29">Galaxy S6</option>
<option value="30">Galaxy F54 5G</option>